name: Bug report
description: Report a reproducible problem in SkyMap Test.
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug.
        Please include clear reproduction steps and expected vs actual behavior.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What went wrong?
      placeholder: A concise summary of the bug.
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: Provide a minimal, deterministic sequence.
      placeholder: |
        1. Open ...
        2. Click ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual behavior
      placeholder: What actually happened?
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: SkyMap version
      placeholder: e.g. 0.1.0
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Windows
        - macOS
        - Linux
        - Web
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste logs or attach a diagnostics bundle.
      render: shell
      placeholder: Paste relevant logs here.

  - type: textarea
    id: diagnostics
    attributes:
      label: Diagnostics bundle note
      description: If you attached diagnostics, mention the filename.
      placeholder: e.g. skymap-diagnostics-2026-02-20T12-34-56-000Z.json
