name: Feature request
description: Suggest an improvement or a new capability.
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea.
        Please describe the problem and proposed solution clearly.

  - type: textarea
    id: problem
    attributes:
      label: Problem / use case
      description: What problem are you trying to solve?
      placeholder: Describe the current limitation.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to happen?
      placeholder: Describe the behavior or UI you expect.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Any workarounds or alternatives you evaluated.

  - type: input
    id: app_version
    attributes:
      label: SkyMap version
      placeholder: e.g. 0.1.0

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Windows
        - macOS
        - Linux
        - Web
        - Other

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Links, screenshots, or extra background.
